# Generated by Django 3.1.3 on 2020-11-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_dare',
            new_name='published_date',
        ),
    ]
